export const DELIVERY_CREATE_REQUEST = 'DELIVERY_CREATE_REQUEST'
export const DELIVERY_CREATE_SUCCESS = 'DELIVERY_CREATE_SUCCESS'
export const DELIVERY_CREATE_FAIL = 'DELIVERY_CREATE_FAIL'
export const DELIVERY_CREATE_RESET = 'DELIVERY_CREATE_RESET'

export const BATCH_DETAIL_REQUEST = 'BATCH_DETAIL_REQUEST'
export const BATCH_DETAIL_SUCCESS = 'BATCH_DETAIL_SUCCESS'
export const BATCH_DETAIL_FAIL = 'BATCH_DETAIL_FAIL'